name: Validate Data Schema

on:
  push:
    paths:
      - 'manager_data_real.csv'
      - 'deliverables/data/*.csv'
  pull_request:
    paths:
      - 'manager_data_real.csv'
      - 'deliverables/data/*.csv'

jobs:
  validate:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas
        
    - name: Validate CSV Schema
      run: |
        python -c "
        import pandas as pd
        import sys
        
        # Check manager_data_real.csv has exactly 18 KPIs + name column
        try:
            df = pd.read_csv('manager_data_real.csv')
            expected_cols = 19  # name + 18 KPIs
            actual_cols = len(df.columns)
            
            print(f'Expected columns: {expected_cols}')
            print(f'Actual columns: {actual_cols}')
            print(f'Column names: {list(df.columns)}')
            
            if actual_cols != expected_cols:
                print(f'ERROR: CSV has {actual_cols} columns but expected {expected_cols}')
                sys.exit(1)
                
            # Check we have exactly 8 managers
            expected_managers = 8
            actual_managers = len(df)
            
            if actual_managers != expected_managers:
                print(f'ERROR: CSV has {actual_managers} managers but expected {expected_managers}')
                sys.exit(1)
                
            print('✅ CSV schema validation passed')
            
        except Exception as e:
            print(f'ERROR: Failed to validate CSV: {e}')
            sys.exit(1)
        "
        
    - name: Check for missing data
      run: |
        python -c "
        import pandas as pd
        import sys
        
        df = pd.read_csv('manager_data_real.csv')
        
        # Check for any completely empty cells
        missing_count = df.isnull().sum().sum()
        
        if missing_count > 0:
            print(f'WARNING: Found {missing_count} missing values in CSV')
            print(df.isnull().sum())
        else:
            print('✅ No missing values found')
        " 